inherit_from: .rubocop_todo.yml

Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/GuardClause:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Lambda:
  Enabled: false

Style/AndOr:
  EnforcedStyle: always

Style/Alias:
  Enabled: false

Metrics/ClassLength:
  CountComments: false
  Max: 1000

Metrics/MethodLength:
  Max: 1000

Metrics/LineLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/PerceivedComplexity:
  Max: 14

Rails/HasAndBelongsToMany:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'config/initializers/*'